version: 2
jobs:
    # The deploy job
    deploy:
        docker:
            - image: circleci/node:8.11.2
        steps:
            - checkout
            # Log the current branch
            - run:
                name: "Checking Versions"
                command: |
                    node --version
                    npm --version
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - persist_to_workspace:
                root: .
                paths: dist
            - run:
                name: Install aws cli
                command:
                    sudo apt-get -y -qq install awscli
            # Set the signature version for the S3 auth
            - run:
                name: Setting Signature Version 4 for S3 Request Authentication
                command: aws configure set default.s3.signature_version s3v4
            # Deploy to the S3 bucket corresponding to the current branch
            - run:
                name: Deploy to S3
                command: |
                    aws --region us-east-1 s3 sync . s3://framexframe.org --delete --exclude 'node_modules/*' --exclude 'src/*'
workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - deploy
